{% set name = "PyLBFGS" %}
{% set version = "0.2.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0394ac3de598b818a01fb225a6b853abbd0e09620e35c072c6c96b0bbe558b99

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lbfgs

about:
  home: https://github.com/dedupeio/pylbfgs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LBFGS and OWL-QN optimization algorithms
  doc_url: https://github.com/dedupeio/pylbfgs
  dev_url: https://github.com/dedupeio/pylbfgs

extra:
  recipe-maintainers:
    - beckermr
