{% set name = "PyLBFGS" %}
{% set version = "0.2.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01b05e381eafaba873453222af527eeb29b2b44771c4523917bd956403e6ceb7

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython <3
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lbfgs

about:
  home: https://github.com/dedupeio/pylbfgs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LBFGS and OWL-QN optimization algorithms
  doc_url: https://github.com/dedupeio/pylbfgs
  dev_url: https://github.com/dedupeio/pylbfgs

extra:
  recipe-maintainers:
    - beckermr
